Repository prplfoundation/prplMesh, pull requests merged in 2020-07, with the labels that each got.

#1503 README.md: add link to latest build artifacts.
  README.md
Labels: ready for merge

#1508 tlvf: remove tlvAlMacAddressType header and source
  framework/tlvf/AutoGenerated/include/tlvf/ieee_1905_1/tlvAlMacAddressType.h
  framework/tlvf/AutoGenerated/src/tlvf/ieee_1905_1/tlvAlMacAddressType.cpp
Labels: ready for merge

#1516 CODEOWNERS: add Mario as a code owner
  CODEOWNERS
Labels: ready for merge

#1511 deploy_firmware.py: don't fail on EOF when device is not reachable
  tools/deploy_firmware.py
Labels: bug, certification, ready for merge

#1500 PPM-220 documentation: Add information about JIRA
  CONTRIBUTING.md
Labels: ready for merge

#1520 controller: db: rename ePersistentParamBool to eTriStateBool
  controller/src/beerocks/master/db/db.cpp
  controller/src/beerocks/master/db/db.h
  controller/src/beerocks/master/db/node.cpp
  controller/src/beerocks/master/db/node.h
Labels: enhancement

#1510 removed the need in nl-tiny. use ln-genl-3 instead
  common/beerocks/bwl/CMakeLists.txt
Labels: ready for merge

#1518 operating class not used in 11k beacon requests
  controller/src/beerocks/master/tasks/association_handling_task.cpp
  controller/src/beerocks/master/tasks/optimal_path_task.cpp
Labels: bug, ready for merge

#1519 increase 11k responsiveness threshold to 80% in optimal path task
  controller/src/beerocks/master/tasks/optimal_path_task.cpp
Labels: ready for merge

#1523 prplmesh utils: increase prplmesh_watchdog sleep time
  common/beerocks/scripts/prplmesh_utils.sh.in
Labels: ready for merge

#1529 CODEOWNERS: add Adam Dov as a code owner
  CODEOWNERS
Labels: ready for merge

#1530 common: bwl: Fix building nl80211 for linux
  common/beerocks/bwl/CMakeLists.txt
Labels: ready for merge

#1542 PPM-255 remove start disabled from main vap hostapd conf
  tools/docker/builder/openwrt/profiles_feeds/netgear-rax40.yml
Labels: ready for merge

#1549 framework: encryption: wps_calculate_keys: use correct kdf length
  framework/common/encryption.cpp
Labels: ready for merge

#1557 .gitlab-ci.yml: boardfarm-tests: add missing dependency on image
  .gitlab-ci.yml
Labels: ready for merge

#1528 Feature/easymesh cert collect hostapd logs
  ci/easymesh_cert_version
Labels: certification

#1566 PPM-319 Fix DCS scan timeout on no results
  common/beerocks/bwl/dwpal/mon_wlan_hal_dwpal.cpp
  common/beerocks/bwl/dwpal/mon_wlan_hal_dwpal.h
Labels: ready for merge

#1553 bwl: dwpal: fix sta_wlan_hal_dwpal::roam return code
  common/beerocks/bwl/dwpal/sta_wlan_hal_dwpal.cpp
Labels: ready for merge

#1546 bwl: nl80211: complete sta_wlan_hal
  common/beerocks/bwl/nl80211/sta_wlan_hal_nl80211.cpp
  common/beerocks/bwl/nl80211/sta_wlan_hal_nl80211.h
Labels: ready for merge

#1554 bwl: dwpal: fix sta_wlan_hal_dwpal::add_network return code
  common/beerocks/bwl/dwpal/sta_wlan_hal_dwpal.cpp
  common/beerocks/bwl/include/bwl/sta_wlan_hal_types.h
Labels: ready for merge

#1565 agent: ucc_listener: take the ssid into account when looking for "mac…
  agent/src/beerocks/slave/agent_db.cpp
  agent/src/beerocks/slave/agent_db.h
  agent/src/beerocks/slave/agent_ucc_listener.cpp
Labels: certification, ready for merge

#1574 bml: rdkb hal: enum elements names conflict with RDKB WiFi HAL ones
  controller/src/beerocks/bml/rdkb/bml_rdkb_defs.h
Labels: bug, ready for merge
