Repository prplfoundation/prplMesh, pull requests merged in 2020-05, with the labels that each got.

#1210 test_gw_repeater.sh: correctly use array for _EXTRA_OPT
  tests/test_gw_repeater.sh
Labels: ready for merge

#1198 DR for 4.7.4 flow (AP Metrics + Policy)
  documentation/flows/agent/ap_metrics.md
  documentation/images/plantuml/agent/flows/ap_metrics.png
  documentation/images/plantuml/agent/flows/ap_metrics.puml
  documentation/images/plantuml/agent/flows/ap_metrics_cert_4.7.4.png
  documentation/images/plantuml/agent/flows/ap_metrics_cert_4.7.4.puml
Labels: ready for merge

#1218 scripts: make owncloud_definitions.sh sourceable
  ci/owncloud/owncloud_definitions.sh
  tools/docker/run.sh
  tools/functions.sh
Labels: ready for merge

#1223 DCS: Scan all available channels
  controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp
Labels: ready for merge

#1161 gitlab-ci: add CI stage with check shell scripts with shellcheck linter
  .gitlab-ci.yml
Labels: ready for merge

#1236 agent: monitor: handle both vendor-specific and ieee1905 messages
  agent/src/beerocks/monitor/monitor_thread.cpp
  agent/src/beerocks/monitor/monitor_thread.h
Labels: ready for merge

#1235 Hotfix/ci/upload artifacts fix typo
  .gitlab-ci.yml
Labels: ready for merge

#1238 tools: builder: openwrt: update to latest prplmesh
  tools/docker/builder/openwrt/build.sh
Labels: ready for merge

#1230 Hotfix/rax40 include kernel modules
  tools/docker/builder/openwrt/Dockerfile
  tools/docker/builder/openwrt/scripts/build.sh
Labels: ready for merge

#1242 agent: backhaul: fix destructor to avoid cppcheck error
  agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp
  ci/cppcheck/cppcheck_existing_issues.txt
Labels: ready for merge

#1219 .gitlab-ci.yml: use verbose mode when running cert tests
  .gitlab-ci.yml
  ci/certification/generic.yml
Labels: ready for merge

#1249 Remove flake8-diff from CI
  .gitlab-ci.yml
Labels: ready for merge

#1251 boardfarm: expose 8002 port in spawned dockerized devices
  tests/boardfarm_plugins/boardfarm_prplmesh/devices/prplmesh_docker.py
Labels: ready for merge

#1250 documentation: agent: add flows for 4.7.6 test
  documentation/flows/agent/ap_metrics.md
  documentation/images/plantuml/agent/flows/ap_metrics_cert_4.7.6.png
  documentation/images/plantuml/agent/flows/ap_metrics_cert_4.7.6.puml
  documentation/images/plantuml/agent/flows/multi_ap_policy_config_request.png
  documentation/images/plantuml/agent/flows/multi_ap_policy_config_request.puml
Labels: ready for merge

#1257 docker: build.sh: add userns keep-id option to be able to run fully unprivileged
  tools/docker/build.sh
Labels: ready for merge

#1252 bwl: add get_survey_info method
  common/beerocks/bwl/dummy/nl80211_client_dummy.cpp
  common/beerocks/bwl/dummy/nl80211_client_dummy.h
  common/beerocks/bwl/include/bwl/nl80211_client.h
  common/beerocks/bwl/shared/nl80211_client_impl.cpp
  common/beerocks/bwl/shared/nl80211_client_impl.h
Labels: ready for merge

#1247 tests: add MAP-4.10.3_ETH to passing tests
  tests/certification/passing_agent_tests.txt
Labels: ready for merge

#1062 coding style: use std algorithm
  CODINGSTYLE.md
Labels: ready for merge

#1248 Hotfix/exit codes
  common/beerocks/scripts/prplmesh_utils.sh.in
Labels: ready for merge

#1277 build.sh: set valid value of docker run option --userns
  tools/docker/build.sh
Labels: bug, ready for merge

#1200 Feature/ci certification use run tests py
  .gitlab-ci.yml
  ci/certification/generic.yml
  ci/run_easymesh_cert.sh
Labels: certification, ready for merge

#1279 tests: capi.py: UCCSocket use longer timeout
  tests/capi.py
Labels: ready for merge

#1256 framework: mapfcommon: change library name from 'common' to 'mapfcommon'
  common/beerocks/bcl/CMakeLists.txt
  common/beerocks/btl/CMakeLists.txt
  framework/CMakeLists.txt
  framework/common/CMakeLists.txt
  framework/common/test/CMakeLists.txt
  framework/common/test/messages/CMakeLists.txt
  framework/platform/bpl/CMakeLists.txt
  framework/platform/bpl/test/CMakeLists.txt
  framework/tlvf/test/CMakeLists.txt
  framework/transport/ieee1905_transport/CMakeLists.txt
  framework/transport/ieee1905_transport/test/CMakeLists.txt
Labels: ready for merge

#1268 bwl: nl80211_client: init attr. validation policy statically
  common/beerocks/bwl/shared/nl80211_client_impl.cpp
Labels: ready for merge

#1294 tools: docker: env variable for image override
  tools/docker/build.sh
  tools/docker/run.sh
Labels: ready for merge

#1297 .gitlab-ci.yml: upload nighlty results to the google sheet
  .gitlab-ci.yml
Labels: certification, ready for merge

#1292 Hotfix/add correct operational class to steering request
  agent/src/beerocks/slave/ap_manager_thread.cpp
  common/beerocks/bwl/dummy/ap_wlan_hal_dummy.cpp
  common/beerocks/bwl/dummy/ap_wlan_hal_dummy.h
  common/beerocks/bwl/dwpal/ap_wlan_hal_dwpal.cpp
  common/beerocks/bwl/dwpal/ap_wlan_hal_dwpal.h
  common/beerocks/bwl/econet/ap_wlan_hal_econet.cpp
  common/beerocks/bwl/econet/ap_wlan_hal_econet.h
  common/beerocks/bwl/include/bwl/ap_wlan_hal.h
  common/beerocks/bwl/nl80211/ap_wlan_hal_nl80211.cpp
  common/beerocks/bwl/nl80211/ap_wlan_hal_nl80211.h
Labels: bug, ready for merge

#1314 .gitlab-ci.yml: upload to the latest folder directly
  .gitlab-ci.yml
Labels: certification, ready for merge

#1260 Added a link to the test setup document
  tests/README.md
Labels: ready for merge

#1318 .mergify.yml: remove status-neutral check
  .mergify.yml
Labels: ready for merge

#1327 Hotfix/Fix disappearing messages bug
  common/beerocks/bcl/include/bcl/beerocks_socket_thread.h
  common/beerocks/bcl/source/beerocks_socket_thread.cpp
  common/beerocks/btl/btl_uds.cpp
  common/beerocks/btl/include/btl/btl.h
Labels: ready for merge

#1315 test_flows.py: disassociate STAs at the end of the test
  tests/test_flows.py
Labels: ready for merge

#1332 docker: openwrt: pass build-arg variables explicitly
  tools/docker/builder/openwrt/build.sh
Labels: ready for merge

#1330 tlvf: CmduMessage: move getClass down to CmduMessageRx
  framework/tlvf/src/include/tlvf/CmduMessage.h
  framework/tlvf/src/include/tlvf/CmduMessageRx.h
Labels: ready for merge

#1331 tests: sniffer: remove length check on tshark list workaround
  tests/sniffer.py
Labels: ready for merge

#1339 tests: sniffer: ignore tshark exit code
  tests/sniffer.py
Labels: ready for merge

#1335 tools: deploy_firmware.py: wait at least for the CAC
  tools/deploy_firmware.py
Labels: certification, ready for merge

#1354 README.md: mention option to make build output more verbose
  tools/docker/README.md
Labels: ready for merge

#1359 Bugfix/dwpal wps pbc update
  common/beerocks/bwl/dwpal/ap_wlan_hal_dwpal.cpp
Labels: certification, ready for merge
