Repository prplfoundation/prplMesh, pull requests merged in 2020-02, with the labels that each got.

#752 Agent UCC listener: support BSSID option
  agent/src/beerocks/slave/agent_ucc_listener.cpp
Labels: certification

#802 controller: ucc listener add dev_get_param support
  controller/src/beerocks/master/controller_ucc_listener.cpp
Labels: :rocket: MergeWhenReady :robot:, certification

#814 controller: Fix unmonitored client issue
  controller/src/beerocks/master/son_actions.cpp
Labels: :rocket: MergeWhenReady :robot:

#849 easylogging: Fix syslog out of memory
  framework/external/easylogging/easylogging++.cc
Labels: MergeWhenReady

#903 Hotfix/fix name of rx phy rate field
  common/beerocks/bwl/nl80211/mon_wlan_hal_nl80211.cpp
Labels: bug
