Repository prplfoundation/prplMesh, pull requests merged in 2020-03, with the labels that each got.

#898 Bugfix/fail to read cross rssi measurement change
  controller/src/beerocks/master/son_master_thread.cpp
Labels: bug

#873 Bugfix for uninitialized variable usage
  agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp
Labels: bug

#935 fix master to build on rdkb
  framework/platform/bpl/uci/cfg/bpl_cfg_uci.h
Labels: bug

#930 Stations remain in blacklist after unblock
  controller/src/beerocks/master/son_actions.cpp
Labels: bug

#938 agent: channel sel: skip non-operable op classes
  agent/src/beerocks/slave/son_slave_thread.cpp
  common/beerocks/bcl/source/son/son_wireless_utils.cpp
Labels: bug, certification

#936 bcl: logging: abort on LOG(FATAL)
  common/beerocks/bcl/source/beerocks_logging.cpp
Labels: enhancement

#948 agent: skip keep alive for non prplmesh controller
  agent/src/beerocks/slave/son_slave_thread.cpp
Labels: bug, certification

#964 agent: channel_sel: ignore channels from other operating classes
  agent/src/beerocks/slave/son_slave_thread.cpp
Labels: bug, certification

#975 agent: topology: don't quit when bh sta is not available
  agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp
Labels: bug, certification

#979 [BUG] agent: autoconfig renew with broadcom controller
  agent/src/beerocks/slave/son_slave_thread.h
Labels: bug, certification, ready for merge

#987 CONTRIBUTING: add an example of a good pull request
  CONTRIBUTING.md
Labels: ready for merge

#993 Hotfix/dynamic channel selection task: increase timeout
  controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp
Labels: ready for merge

#999 .gitlab-ci.yml: cppcheck: run on the framework folder
  .gitlab-ci.yml
Labels: ready for merge

#989 tools: clang-format: run only on tracked files
  clang-format.sh
  tools/docker/clang-format.sh
Labels: ready for merge

#988 controller: task: simplify event_received
  controller/src/beerocks/master/tasks/task.cpp
Labels: ready for merge

#1014 Agent: Variable overflow in fill_cs_params
  agent/src/beerocks/slave/ap_manager_thread.cpp
  common/beerocks/bwl/dummy/ap_wlan_hal_dummy.cpp
Labels: ready for merge

#1028 slave: send ack to controller on opportunity steering request
  agent/src/beerocks/slave/son_slave_thread.cpp
Labels: certification, ready for merge

#1045 controller: fix compilation error on rdkb
  controller/src/beerocks/master/tasks/rdkb/rdkb_wlan_task_db.cpp
Labels: ready for merge

#1044 build: change CMAKE REVISION variable to PRPLMESH_REVISION
  agent/CMakeLists.txt
  cmake/multiap-helpers.cmake
  controller/CMakeLists.txt
  tools/docker/builder/openwrt/build.sh
  version.in
Labels: ready for merge

#1034 Agent: Does not send operating channel report
  agent/src/beerocks/slave/son_slave_thread.cpp
Labels: ready for merge

#1047 hotfix/Fix missing client RSSI on multiple reconnects
  controller/src/beerocks/master/son_actions.cpp
Labels: ready for merge

#1041 openwrt build.sh use TARGET_DEVICE for default
  tools/docker/builder/openwrt/build.sh
Labels: ready for merge

#1036 CODINGSTYLE: add object types section
  CODINGSTYLE.md
Labels: ready for merge
