Repository prplfoundation/prplMesh, pull requests merged in 2020-06, with the labels that each got.

#1374 [BUG] agent: Documentation for channel selection request
  documentation/images/plantuml/agent/flows/channel_selection.png
  documentation/images/plantuml/agent/flows/channel_selection.puml
Labels: ready for merge

#1367 [RFC] framework: remove examples
  framework/CMakeLists.txt
  framework/README.md
  framework/examples/CMakeLists.txt
  framework/examples/transport/CMakeLists.txt
  framework/examples/transport/multiap_agent.cpp
  framework/examples/transport/multiap_common.h
  framework/examples/transport/multiap_controller.cpp
  framework/examples/zmq/C/CMakeLists.txt
  framework/examples/zmq/CMakeLists.txt
  framework/examples/zmq/CPP/CMakeLists.txt
Labels: ready for merge

#1366 bwl: remove econet version
  ci/cppcheck/cppcheck_existing_issues.txt
  common/beerocks/bwl/econet/README.md
  common/beerocks/bwl/econet/ap_wlan_hal_econet.cpp
  common/beerocks/bwl/econet/ap_wlan_hal_econet.h
  common/beerocks/bwl/econet/base_wlan_hal_econet.cpp
  common/beerocks/bwl/econet/base_wlan_hal_econet.h
  common/beerocks/bwl/econet/mon_wlan_hal_econet.cpp
  common/beerocks/bwl/econet/mon_wlan_hal_econet.h
  common/beerocks/bwl/econet/sta_wlan_hal_econet.cpp
  common/beerocks/bwl/econet/sta_wlan_hal_econet.h
Labels: ready for merge

#1382 agent: monitor: avoid reporting unitialized vap stats
  agent/src/beerocks/monitor/monitor_db.h
  agent/src/beerocks/monitor/monitor_thread.cpp
Labels: certification, focus, ready for merge

#1388 agent: backhaul_manager: fix test 4.7.5
  agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp
Labels: certification, focus, ready for merge

#1316 deploy_ipk.sh: adding force dependencies on rdkb platform
  tools/deploy_ipk.sh
Labels: ready for merge

#1356 prplmesh_utils.sh.in: use BEEROCKS vars instead of hard-coded wlan0/2
  common/beerocks/scripts/prplmesh_utils.sh.in
Labels: ready for merge

#1343 hotfix! Fix data filling in add_ap_metrics
  agent/src/beerocks/monitor/monitor_db.h
  agent/src/beerocks/monitor/monitor_stats.cpp
  agent/src/beerocks/monitor/monitor_stats.h
  agent/src/beerocks/monitor/monitor_thread.cpp
Labels: ready for merge

#1392 easylogging: log uint8_t as int
  framework/external/easylogging/easylogging++.h
Labels: ready for merge

#1389 certification: add MAP-4.10.4 to the list of passing tests
  tests/certification/passing_agent_tests.txt
Labels: certification, focus, ready for merge

#1357 cmake: allow redefinition BEEROCKS_* vars from cmdline
  CMakeLists.txt
  common/CMakeLists.txt
  common/beerocks/bwl/CMakeLists.txt
Labels: bug, ready for merge

#1336 bwl: Fix parsing of DFS-CAC-COMPLETED dwpal event
  common/beerocks/bwl/dwpal/ap_wlan_hal_dwpal.cpp
Labels: ready for merge

#1402 passing_agent_tests.txt: order like all_agent_tests.txt
  tests/certification/passing_agent_tests.txt
Labels: ready for merge

#1379 ci:tests:parse log file correctly even if the encoding is wrong
  tests/environment.py
Labels: ready for merge

#1403 Update AUTHORS.md file
  AUTHORS.md
Labels: ready for merge

#1407 Hotfix/docker openwrt builder
  tools/docker/builder/openwrt/Dockerfile
Labels: ready for merge

#1409 bugfix
  controller/src/beerocks/master/db/db.cpp
Labels: ready for merge

#1411 Bugfix / update dwpal_bw_to_beerocks_bw to fit eWiFiBandwidth
  common/beerocks/bwl/dwpal/ap_wlan_hal_dwpal.cpp
Labels: ready for merge

#1433 cmake: Finddwpal.cmake add opt/intel/lib
  cmake/Finddwpal.cmake
Labels: ready for merge

#1417 Update the copyright message in the beerocks version class
  common/beerocks/bcl/source/beerocks_version.cpp
Labels: ready for merge

#1431 Controller: bml_conn_map output fix
  controller/src/beerocks/bml/bml_utils.cpp
Labels: ready for merge

#1437 deploy_firmware.py: try to kill the prplMesh init script first
  tools/deploy_firmware.py
Labels: bug, ready for merge

#1441 Format BTLVF yaml files
  common/beerocks/tlvf/yaml/beerocks/tlvf/beerocks_message_1905_vs.yaml
  common/beerocks/tlvf/yaml/beerocks/tlvf/beerocks_message_action.yaml
  common/beerocks/tlvf/yaml/beerocks/tlvf/beerocks_message_apmanager.yaml
  common/beerocks/tlvf/yaml/beerocks/tlvf/beerocks_message_backhaul.yaml
  common/beerocks/tlvf/yaml/beerocks/tlvf/beerocks_message_bml.yaml
  common/beerocks/tlvf/yaml/beerocks/tlvf/beerocks_message_cli.yaml
  common/beerocks/tlvf/yaml/beerocks/tlvf/beerocks_message_cli_net_map.yaml
  common/beerocks/tlvf/yaml/beerocks/tlvf/beerocks_message_control.yaml
  common/beerocks/tlvf/yaml/beerocks/tlvf/beerocks_message_header.yaml
  common/beerocks/tlvf/yaml/beerocks/tlvf/beerocks_message_monitor.yaml
  common/beerocks/tlvf/yaml/beerocks/tlvf/beerocks_message_platform.yaml
Labels: ready for merge

#1419 [documentation] Add UML diaram for Backhaul STA steering
  documentation/images/plantuml/agent/flows/bh_sta_steering.png
  documentation/images/plantuml/agent/flows/bh_sta_steering.puml
Labels: ready for merge

#1451 slave: backhaul manager: fixed weird curly brackets
  agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp
Labels: ready for merge

#1410 Feature / update the prplMesh utils operation test to use BML
  common/beerocks/scripts/prplmesh_utils.sh.in
Labels: ready for merge

#1454 use SIGTERM instead of SIGKILL in killall_program()
  common/beerocks/scripts/prplmesh_utils.sh.in
Labels: ready for merge

#1458 Use neighbor's interface info in Topology Response
  agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp
Labels: ready for merge

#1429 Feature/unified agent infrastructure
  agent/src/beerocks/slave/agent_db.h
Labels: ready for merge

#1477 Hotfix/fix media type typo
  agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp
  agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.h
  framework/tlvf/AutoGenerated/include/tlvf/ieee_1905_1/eMediaType.h
  framework/tlvf/README.md
  framework/tlvf/yaml/tlvf/ieee_1905_1/eMediaType.yaml
Labels: ready for merge

#1478 prplmesh_utils.sh: send SIGKILL after SIGTERM
  common/beerocks/scripts/prplmesh_utils.sh.in
Labels: ready for merge

#1365 bcl: wireless_unit_test: use parameters for GetOperatingClassByChannelTest
  common/beerocks/bcl/source/son/son_wireless_utils.cpp
  common/beerocks/bcl/unit_tests/wireless_utils_test.cpp
Labels: ready for merge

#1487 VSCode Settings Update
  .vscode/settings.json
Labels: ready for merge

#1465 hotfix! Change bssid type for roam() method
  agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp
  common/beerocks/bwl/dummy/sta_wlan_hal_dummy.cpp
  common/beerocks/bwl/dummy/sta_wlan_hal_dummy.h
  common/beerocks/bwl/dwpal/sta_wlan_hal_dwpal.cpp
  common/beerocks/bwl/dwpal/sta_wlan_hal_dwpal.h
  common/beerocks/bwl/include/bwl/sta_wlan_hal.h
  common/beerocks/bwl/nl80211/sta_wlan_hal_nl80211.cpp
  common/beerocks/bwl/nl80211/sta_wlan_hal_nl80211.h
Labels: ready for merge

#1471 [agent] Add validate_channel method
  common/beerocks/bcl/include/bcl/son/son_wireless_utils.h
  common/beerocks/bcl/source/son/son_wireless_utils.cpp
Labels: ready for merge
