Repository prplfoundation/prplMesh, pull requests merged in 2020-04, with the labels that each got.

#965 test_flows.py: Enhance channel selection test
  tests/test_flows.py
Labels: ready for merge

#1032 documentation: prplMesh to boarfarm integration
  documentation/images/plantuml/boardfarm_prplMesh_classes.puml
  documentation/images/plantuml/boardfarm_prplMesh_test_setup.puml
Labels: architecture, ready for merge

#1061 check rdkb wlan task state before handling steering socket remove event
  controller/src/beerocks/master/tasks/rdkb/rdkb_wlan_task.cpp
  controller/src/beerocks/master/tasks/rdkb/rdkb_wlan_task.h
Labels: bug, ready for merge

#1053 [BUG] bwl: missing channels when using nl80211_client::get_radio_info
  common/beerocks/bwl/shared/netlink_socket.cpp
  common/beerocks/bwl/shared/netlink_socket.h
  common/beerocks/bwl/shared/nl80211_client_impl.cpp
  common/beerocks/bwl/shared/nl80211_socket.cpp
  common/beerocks/bwl/shared/nl80211_socket.h
Labels: ready for merge

#1043 bwl: refactor read_supported_channels to use get_radio_info
  common/beerocks/bwl/dwpal/ap_wlan_hal_dwpal.cpp
  common/beerocks/bwl/nl80211/ap_wlan_hal_nl80211.cpp
Labels: ready for merge

#1092 hotfix: set_tx_power_limit()
  common/beerocks/bwl/dummy/ap_wlan_hal_dummy.cpp
Labels: ready for merge

#1109 CODEOWNERS: Add Vitaly Bukhovsky as a code owner
  CODEOWNERS
Labels: ready for merge

#1111 agent: backhaul_manager: get_media_type(): return true on success
  agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp
Labels: bug, ready for merge

#1000 PORTING.md: initial porting guide
  PORTING.md
Labels: ready for merge

#980 documentation: test_flows.py test description
  tests/README.md
Labels: enhancement, ready for merge

#1115 CODINGSTYLE.md: Add multiple vs single point of exit
  CODINGSTYLE.md
Labels: ready for merge

#1106 scripts: tools/docker/run.sh: fix usage docker network name passed via cmdline arg
  tests/test_gw_repeater.sh
  tools/docker/run.sh
Labels: ready for merge

#1129 Readme.md: add troubleshooting for master branch
  README.md
Labels: ready for merge

#1144 CONTRIBUTING.md: add a paragraph about clang-format and flake8
  CONTRIBUTING.md
Labels: ready for merge

#1150 agent: monitor: remove duplicate call to now()
  agent/src/beerocks/monitor/monitor_thread.cpp
  ci/cppcheck/cppcheck_existing_issues.txt
Labels: ready for merge

#1169 ci: certification: add all remaining wired backhaul tests
  ci/certification/netgear-rax40.yml
Labels: certification, ready for merge

#1147 tools: docker: README.md: add docker logs to the cheatsheet
  tools/docker/README.md
Labels: ready for merge

#1165 tests: add a list with all the MAUT tests we can currently pass
  tests/certification/passing_agent_tests.txt
Labels: certification, ready for merge

#1171 CONTRIBUTING.md: definition of done: add passing_agent_tests.txt
  CONTRIBUTING.md
Labels: ready for merge

#1173 update iterator after erase
  agent/src/beerocks/monitor/monitor_db.cpp
  agent/src/beerocks/monitor/monitor_thread.cpp
  agent/src/beerocks/slave/ap_manager_thread.cpp
  agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp
  common/beerocks/bwl/dwpal/ap_wlan_hal_dwpal.cpp
  controller/src/beerocks/cli/beerocks_cli_proxy.cpp
  controller/src/beerocks/master/db/db.cpp
  controller/src/beerocks/master/tasks/channel_selection_task.cpp
  controller/src/beerocks/master/tasks/rdkb/rdkb_wlan_task.cpp
  controller/src/beerocks/master/tasks/rdkb/rdkb_wlan_task_db.cpp
  controller/src/beerocks/master/tasks/task.cpp
  framework/common/nng/socket.cpp
  framework/common/zmq/poller.cpp
  framework/common/zmq/socket.cpp
  framework/platform/bpl/uci/arp/monitor/arp_monitor.cpp
Labels: ready for merge

#1181 Add MAP-4.6.1_ETH to passing tests
  tests/certification/passing_agent_tests.txt
Labels: ready for merge

#1196 tools: openwrt: update feed-prpl hash
  tools/docker/builder/openwrt/build.sh
Labels: ready for merge

#1177 tests: README.md: add API description for writing tests
  tests/README.md
Labels: ready for merge

#1203 Fix typo in handle_1905_autoconfiguration_response
  agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp
Labels: ready for merge

#1207 tests: openwrt: save hostapd configuration files
  .gitlab-ci.yml
  tests/openwrt/test_status.sh
Labels: ready for merge

#1206 .gitlab-ci.yml: test-on-target: set a timeout
  .gitlab-ci.yml
Labels: ready for merge

#1093 Feature/channel pool validation
  controller/src/beerocks/master/db/db.cpp
  controller/src/beerocks/master/db/db.h
Labels: ready for merge

#1201 tests: initial_ap_config.py: remove utils.py class
  tests/boardfarm_plugins/boardfarm_prplmesh/tests/initial_ap_config.py
  tests/boardfarm_plugins/boardfarm_prplmesh/tests/prplmesh_base_test.py
Labels: enhancement, ready for merge

#1212 .gitlab-ci.yml: only keep the latest build for the master branch
  .gitlab-ci.yml
Labels: ready for merge
